theme: jekyll-theme-architect
title: AddAttachment Unity page
description: page to download the packages for Pico Neo 3 Pro Eye device
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
 show_downloads: true 
    github:  
      zip_url: https://github.com/luca-arts/addattachment-unity/blob/gh-pages/Android/Android.apk
